### ISSUE TITLE
Usage or integration of WiZ dimmable plug

### ISSUE THREAD

**Issue by fonk** [frejos/openhab-wizlighting#2]
Hi!

Is it expected that a WiZ dimmable plug (https://www.amazon.de/WiZ-Wiz-Intelligente-WLAN-Steckdose/dp/B08HLQ8PK1) will already work with this binding? As far as I know, this would be the only dimmable EU-plug which works with OpenHAB ;-)
If it's expected to work, I will order one to test - otherwise I would also donate one, if you like to try an integration!

Best regards,
Frank

**Comment by frejos** [comment]
Hi Frank,

I have not tested this device so can't say for certain that it will work. However, based on what I've seen from other WiZ devices I think the chances are good that it will just work (although it might get detected incorrectly). I have tested the US switchable (not dimmable) plug and it detects and functions as expected. If you get one let me know how it goes. As long as they haven't changed something substantial, it probably would only take a few minor tweaks to the code worst case.

Thanks,

Josh

**Comment by fonk** [comment]
Hi Josh,
thanks for the fast response! I just ordered four of them and they're announced to be here in about one week. I will report the results and hope you can support in the case they're not working out-of-the box :-)
Best regards,
Frank

**Comment by frejos** [comment]
Good luck! Before you plug these in, I would suggest going ahead and turning the logging up to the TRACE level for the org.openhab.binding.wizlighting.internal.discovery.WizLightingDiscoveryService class. You can do that using the openhab console command line interface. That will print out all the information in the logs about the discovery process and will be useful if it doesn't work right away. Let me know how it goes and I'll do my best to help out.

**Comment by fonk** [comment]
Hi Joah,
I today tested the devices: Good news for you: They're working out of the box. Bad new for me: Seems like they don't have the promised dimmer functionality (=misinformation on merchant page) :-(
Nevertheless, here are the debug log in case they're of any interest for you:
11:37:10.020 [TRACE] [discovery.WizLightingDiscoveryService] - New bulb discovered at 192.168.66.49 with MAC 6c2990a9af03.  Requesting configuration info from the bulb.
11:37:10.032 [DEBUG] [discovery.WizLightingDiscoveryService] - Sent packet to address: /192.168.66.49 and port 38899
11:37:10.061 [TRACE] [discovery.WizLightingDiscoveryService] - Returned model from discovered bulb at 192.168.66.49: ESP10_SOCKET_06
11:37:10.072 [TRACE] [discovery.WizLightingDiscoveryService] - New device appears to be a smart plug and will be given the UUID: wizlighting:wizPlug:6c2990a9af03
11:37:10.098 [INFO ] [openhab.event.InboxAddedEvent        ] - Discovery Result with UID 'wizlighting:wizPlug:6c2990a9af03' has been added.
11:37:10.097 [INFO ] [ig.discovery.internal.PersistentInbox] - Added new thing 'wizlighting:wizPlug:6c2990a9af03' to inbox.
11:37:15.134 [TRACE] [discovery.WizLightingDiscoveryService] - New bulb discovered at 192.168.66.49 with MAC 6c2990a9af03.  Requesting configuration info from the bulb.
11:37:15.146 [DEBUG] [discovery.WizLightingDiscoveryService] - Sent packet to address: /192.168.66.49 and port 38899
11:37:15.227 [TRACE] [discovery.WizLightingDiscoveryService] - Returned model from discovered bulb at 192.168.66.49: ESP10_SOCKET_06
11:37:15.235 [TRACE] [discovery.WizLightingDiscoveryService] - New device appears to be a smart plug and will be given the UUID: wizlighting:wizPlug:6c2990a9af03
11:37:20.079 [TRACE] [discovery.WizLightingDiscoveryService] - New bulb discovered at 192.168.66.49 with MAC 6c2990a9af03.  Requesting configuration info from the bulb.
11:37:20.091 [DEBUG] [discovery.WizLightingDiscoveryService] - Sent packet to address: /192.168.66.49 and port 38899
11:37:20.104 [TRACE] [discovery.WizLightingDiscoveryService] - Returned model from discovered bulb at 192.168.66.49: ESP10_SOCKET_06
11:37:20.112 [TRACE] [discovery.WizLightingDiscoveryService] - New device appears to be a smart plug and will be given the UUID: wizlighting:wizPlug:6c2990a9af03
11:37:25.091 [TRACE] [discovery.WizLightingDiscoveryService] - New bulb discovered at 192.168.66.49 with MAC 6c2990a9af03.  Requesting configuration info from the bulb.
11:37:25.104 [DEBUG] [discovery.WizLightingDiscoveryService] - Sent packet to address: /192.168.66.49 and port 38899
11:37:25.129 [TRACE] [discovery.WizLightingDiscoveryService] - Returned model from discovered bulb at 192.168.66.49: ESP10_SOCKET_06
11:37:25.137 [TRACE] [discovery.WizLightingDiscoveryService] - New device appears to be a smart plug and will be given the UUID: wizlighting:wizPlug:6c2990a9af03
11:37:33.051 [TRACE] [discovery.WizLightingDiscoveryService] - New bulb discovered at 192.168.66.49 with MAC 6c2990a9af03.  Requesting configuration info from the bulb.
11:37:33.063 [DEBUG] [discovery.WizLightingDiscoveryService] - Sent packet to address: /192.168.66.49 and port 38899
11:37:33.084 [TRACE] [discovery.WizLightingDiscoveryService] - Returned model from discovered bulb at 192.168.66.49: ESP10_SOCKET_06
11:37:33.095 [TRACE] [discovery.WizLightingDiscoveryService] - New device appears to be a smart plug and will be given the UUID: wizlighting:wizPlug:6c2990a9af03
11:37:38.083 [TRACE] [discovery.WizLightingDiscoveryService] - New bulb discovered at 192.168.66.49 with MAC 6c2990a9af03.  Requesting configuration info from the bulb.
11:37:38.094 [DEBUG] [discovery.WizLightingDiscoveryService] - Sent packet to address: /192.168.66.49 and port 38899
11:37:38.110 [TRACE] [discovery.WizLightingDiscoveryService] - Returned model from discovered bulb at 192.168.66.49: ESP10_SOCKET_06
11:37:38.118 [TRACE] [discovery.WizLightingDiscoveryService] - New device appears to be a smart plug and will be given the UUID: wizlighting:wizPlug:6c2990a9af03
11:37:43.081 [TRACE] [discovery.WizLightingDiscoveryService] - New bulb discovered at 192.168.66.49 with MAC 6c2990a9af03.  Requesting configuration info from the bulb.
11:37:43.094 [DEBUG] [discovery.WizLightingDiscoveryService] - Sent packet to address: /192.168.66.49 and port 38899
11:37:43.115 [TRACE] [discovery.WizLightingDiscoveryService] - Returned model from discovered bulb at 192.168.66.49: ESP10_SOCKET_06
11:37:43.122 [TRACE] [discovery.WizLightingDiscoveryService] - New device appears to be a smart plug and will be given the UUID: wizlighting:wizPlug:6c2990a9af03

**Comment by frejos** [comment]
Ah, sorry to hear that. Just out of curiosity, did the dimming function not work from the Wiz App itself? I see that it was detected as a plug by the binding, which does not have a Brightness channel configured on it in the binding. So just wanted to make sure you checked from the Wiz App to be sure it doesn't support dimming.

**Comment by fonk** [comment]
Hi Josh,
yes, even in the Wiz App is no dimming function, thus it's not the binding. If anyone reading this threat knows about an OpenHab compatible dimmable plug/jack, please let me know! :-)

**Comment by frejos** [comment]
Ah dang, sorry about that. Best of luck and thanks for the logs and validating that the switchable part of the plugs work.
